"use client";
import React, { useState, useEffect } from "react";
import OpenAI from "openai";

const openai = new OpenAI({
  apiKey:
    "sk-bpVg50afhh0TSnh3EgewxTyiUgN_5ZiJc8iMx5QqI2T3BlbkFJrTZEo-YBWqDSMnfFbHYtJAn8RgktF9INtMjGjUVwYA",
  dangerouslyAllowBrowser: true,
});

export default function page() {
  const [imageUrl, setImageUrl] = useState(null); // State to store the generated image URL
  const [loading, setLoading] = useState(false); // State to manage loading state
  const [error, setError] = useState(null); // State to manage errors

  const generateImage = async () => {
    setLoading(true);
    setError(null); // Reset any previous errors
    try {
      const response = await openai.images.generate({
        model: "dall-e-3",
        prompt: "openbox soccer match day", // You can customize this prompt
        n: 1,
        size: "1024x1024",
      });

      const image_url = response.data[0].url;
      setImageUrl(image_url);
    } catch (err) {
      setError("Failed to generate image. Please try again.");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center p-4">
      <h2 className="text-2xl font-bold mb-4">DALL-E Image Generator</h2>

      <button
        onClick={generateImage}
        className="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-700 transition duration-300"
        disabled={loading}
      >
        {loading ? "Generating..." : "Generate Image"}
      </button>

      {error && <p className="text-red-500 mt-4">{error}</p>}

      {imageUrl && (
        <div className="mt-6">
          <img
            src={imageUrl}
            alt="Generated by DALL-E"
            className="w-64 h-64 object-cover rounded-lg shadow-lg"
          />
        </div>
      )}
    </div>
  );
}
